apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/donneypr/homelab.git
    targetRevision: main
    path: clusters/prod/manifests/podinfo-ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: podinfo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
